from decimal import Decimal
from datetime import datetime
from threading import Lock
from urllib.parse import urlparse

import psycopg
from psycopg.rows import dict_row

from config import DATABASE_URL, IST, SQLITE_PATH, TRACKED_INDEXES, symbol_for_index

_init_lock = Lock()
_initialized = False

SCHEMA = """
CREATE TABLE IF NOT EXISTS dataset_status (
    dataset TEXT NOT NULL,
    month TEXT NOT NULL,
    as_of_date TEXT,
    status TEXT NOT NULL,
    source TEXT,
    source_url TEXT,
    scraped_at TEXT,
    error TEXT,
    PRIMARY KEY (dataset, month)
);

CREATE TABLE IF NOT EXISTS institutional_flows (
    month TEXT NOT NULL,
    as_of_date TEXT NOT NULL,
    category TEXT NOT NULL,
    buy_value DOUBLE PRECISION,
    sell_value DOUBLE PRECISION,
    net_flow DOUBLE PRECISION,
    source TEXT NOT NULL,
    source_url TEXT,
    scraped_at TEXT NOT NULL,
    status TEXT NOT NULL,
    UNIQUE(month, category)
);

CREATE TABLE IF NOT EXISTS institutional_flow_daily (
    trade_date TEXT NOT NULL,
    category TEXT NOT NULL,
    buy_value DOUBLE PRECISION,
    sell_value DOUBLE PRECISION,
    net_flow DOUBLE PRECISION,
    source TEXT NOT NULL,
    source_url TEXT,
    scraped_at TEXT NOT NULL,
    UNIQUE(trade_date, category)
);

CREATE TABLE IF NOT EXISTS sector_fpi_flows (
    month TEXT NOT NULL,
    sector TEXT NOT NULL,
    period_type TEXT NOT NULL,
    period_end TEXT NOT NULL,
    equity_net DOUBLE PRECISION,
    source TEXT,
    source_url TEXT,
    scraped_at TEXT,
    status TEXT,
    UNIQUE(month, sector, period_type, period_end)
);

CREATE TABLE IF NOT EXISTS mutual_fund_flows (
    month TEXT NOT NULL,
    as_of_date TEXT,
    equity_inflow DOUBLE PRECISION,
    equity_outflow DOUBLE PRECISION,
    equity_net DOUBLE PRECISION,
    sip_contribution DOUBLE PRECISION,
    equity_aum DOUBLE PRECISION,
    large_cap_net DOUBLE PRECISION,
    mid_cap_net DOUBLE PRECISION,
    small_cap_net DOUBLE PRECISION,
    etf_net DOUBLE PRECISION,
    source TEXT,
    source_url TEXT,
    scraped_at TEXT,
    status TEXT,
    UNIQUE(month)
);

CREATE TABLE IF NOT EXISTS market_performance (
    month TEXT NOT NULL,
    as_of_date TEXT NOT NULL,
    nifty50_close DOUBLE PRECISION,
    nifty50_ret_1w DOUBLE PRECISION,
    nifty50_ret_1m DOUBLE PRECISION,
    nifty50_ret_3m DOUBLE PRECISION,
    nifty50_ret_6m DOUBLE PRECISION,
    nifty50_ret_ytd DOUBLE PRECISION,
    nifty50_ret_1y DOUBLE PRECISION,
    nifty500_close DOUBLE PRECISION,
    nifty500_ret_1w DOUBLE PRECISION,
    nifty500_ret_1m DOUBLE PRECISION,
    nifty500_ret_3m DOUBLE PRECISION,
    nifty500_ret_6m DOUBLE PRECISION,
    nifty500_ret_ytd DOUBLE PRECISION,
    nifty500_ret_1y DOUBLE PRECISION,
    source TEXT,
    source_url TEXT,
    scraped_at TEXT,
    status TEXT,
    UNIQUE(month)
);

CREATE TABLE IF NOT EXISTS sector_performance (
    month TEXT NOT NULL,
    as_of_date TEXT NOT NULL,
    sector TEXT NOT NULL,
    close DOUBLE PRECISION,
    ret_1w DOUBLE PRECISION,
    ret_1m DOUBLE PRECISION,
    ret_3m DOUBLE PRECISION,
    ret_6m DOUBLE PRECISION,
    ret_ytd DOUBLE PRECISION,
    ret_1y DOUBLE PRECISION,
    source TEXT,
    source_url TEXT,
    scraped_at TEXT,
    status TEXT,
    UNIQUE(month, sector)
);

CREATE TABLE IF NOT EXISTS sector_relative_strength (
    month TEXT NOT NULL,
    as_of_date TEXT NOT NULL,
    sector TEXT NOT NULL,
    vs_nifty500_1m DOUBLE PRECISION,
    vs_nifty500_3m DOUBLE PRECISION,
    source TEXT,
    source_url TEXT,
    scraped_at TEXT,
    status TEXT,
    UNIQUE(month, sector)
);

CREATE TABLE IF NOT EXISTS sector_money_flow_score (
    month TEXT NOT NULL,
    as_of_date TEXT NOT NULL,
    sector TEXT NOT NULL,
    score DOUBLE PRECISION,
    institutional_score DOUBLE PRECISION,
    price_score DOUBLE PRECISION,
    rs_score DOUBLE PRECISION,
    signal TEXT,
    category TEXT,
    source TEXT,
    source_url TEXT,
    scraped_at TEXT,
    status TEXT,
    UNIQUE(month, sector)
);

CREATE TABLE IF NOT EXISTS daily_indices (
    trade_date TEXT NOT NULL,
    index_name TEXT NOT NULL,
    symbol TEXT,
    close DOUBLE PRECISION,
    volume DOUBLE PRECISION,
    turnover DOUBLE PRECISION,
    UNIQUE(trade_date, index_name)
);

CREATE TABLE IF NOT EXISTS scrape_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TEXT,
    finished_at TEXT,
    historical_updated INTEGER DEFAULT 0,
    historical_skipped INTEGER DEFAULT 0,
    current_updated INTEGER DEFAULT 0,
    errors INTEGER DEFAULT 0,
    summary TEXT
);
"""

TABLES = [
    "dataset_status",
    "institutional_flows",
    "institutional_flow_daily",
    "sector_fpi_flows",
    "mutual_fund_flows",
    "market_performance",
    "sector_performance",
    "sector_relative_strength",
    "sector_money_flow_score",
    "daily_indices",
    "scrape_runs",
]

STOCK_TABLES = [
    "daily_prices",
    "constituents",
    "market_breadth",
    "sector_breadth",
    "sector_volume",
    "darvas_breakouts",
    "stock_industry",
    "daily_bhav",
]


def _purge_unused_indexes(conn: "PgConn") -> None:
    placeholders = ", ".join("?" for _ in TRACKED_INDEXES)
    conn.execute(
        f"DELETE FROM daily_indices WHERE index_name NOT IN ({placeholders})",
        TRACKED_INDEXES,
    )


def _backfill_index_symbols(conn: "PgConn") -> None:
    missing = conn.execute(
        "SELECT COUNT(*) AS n FROM daily_indices WHERE symbol IS NULL OR symbol=''"
    ).fetchone()
    if missing and not missing["n"]:
        return
    names = conn.execute(
        "SELECT DISTINCT index_name FROM daily_indices WHERE symbol IS NULL OR symbol=''"
    ).fetchall()
    for row in names:
        name = row["index_name"]
        conn.execute(
            "UPDATE daily_indices SET symbol=? WHERE index_name=?",
            (symbol_for_index(name), name),
        )
    conn.commit()


def now_iso() -> str:
    return datetime.now(IST).isoformat(timespec="seconds")


def _adapt(sql: str) -> str:
    return sql.replace("?", "%s")


def _clean(value):
    if isinstance(value, Decimal):
        return float(value)
    return value


def _clean_row(row):
    if row is None:
        return None
    return {k: _clean(v) for k, v in dict(row).items()}


class PgCursor:
    def __init__(self, cur):
        self._cur = cur

    def fetchone(self):
        return _clean_row(self._cur.fetchone())

    def fetchall(self):
        return [_clean_row(r) for r in self._cur.fetchall()]

    def __iter__(self):
        for row in self._cur:
            yield _clean_row(row)


class PgConn:
    def __init__(self, raw: psycopg.Connection):
        self._raw = raw

    def execute(self, sql: str, args=()):
        cur = self._raw.cursor()
        cur.execute(_adapt(sql), tuple(args) if args is not None else None)
        return PgCursor(cur)

    def executemany(self, sql: str, seq):
        cur = self._raw.cursor()
        cur.executemany(_adapt(sql), seq)
        return PgCursor(cur)

    def executescript(self, script: str) -> None:
        for part in script.split(";"):
            stmt = part.strip()
            if stmt:
                self._raw.execute(stmt)

    def commit(self) -> None:
        self._raw.commit()

    def close(self) -> None:
        self._raw.close()


def connect() -> PgConn:
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL is not set. Add it to .env")
    kwargs = {"row_factory": dict_row, "connect_timeout": 30}
    host = urlparse(DATABASE_URL).hostname
    ip = _resolve_ipv4(host) if host else None
    if ip:
        kwargs["hostaddr"] = ip
    try:
        raw = psycopg.connect(DATABASE_URL, **kwargs)
    except Exception as exc:
        raise RuntimeError(
            "Could not connect to Postgres. On IPv4-only networks use the "
            "Session pooler URI from Supabase Connect (port 5432)."
        ) from exc
    return PgConn(raw)


def _resolve_ipv4(host: str) -> str | None:
    import socket
    import subprocess

    try:
        return socket.getaddrinfo(host, 5432, socket.AF_INET, socket.SOCK_STREAM)[0][4][0]
    except OSError:
        pass
    for args in (
        ["dig", "+short", host, "A"],
        ["nslookup", host, "8.8.8.8"],
    ):
        try:
            out = subprocess.check_output(args, text=True, timeout=8)
        except (FileNotFoundError, subprocess.CalledProcessError, subprocess.TimeoutExpired):
            continue
        found = None
        for line in out.splitlines():
            line = line.strip()
            if not line or line.startswith(";"):
                continue
            if "Address:" in line:
                line = line.split("Address:", 1)[1].strip()
            cand = line.split("#", 1)[0].strip()
            if cand.count(".") == 3 and all(p.isdigit() for p in cand.split(".")) and cand != "8.8.8.8":
                found = cand
        if found:
            return found
    return None


def init_db() -> None:
    global _initialized
    if _initialized:
        return
    with _init_lock:
        if _initialized:
            return
        conn = connect()
        conn.executescript(SCHEMA)
        conn.execute("ALTER TABLE daily_indices ADD COLUMN IF NOT EXISTS symbol TEXT")
        for table in STOCK_TABLES:
            conn.execute(f"DROP TABLE IF EXISTS {table}")
        conn.execute(
            "DELETE FROM dataset_status WHERE dataset IN ('market_breadth', 'volume', 'darvas')"
        )
        _purge_unused_indexes(conn)
        for col in ("breadth_score", "volume_score", "breakout_score"):
            conn.execute(f"ALTER TABLE sector_money_flow_score DROP COLUMN IF EXISTS {col}")
        conn.commit()
        _backfill_index_symbols(conn)
        _maybe_migrate_sqlite(conn)
        conn.close()
        _initialized = True


def upsert(conn: PgConn, table: str, row: dict, conflict: str, replace: bool = True) -> None:
    cols = list(row.keys())
    placeholders = ", ".join("?" for _ in cols)
    if replace:
        assignments = ", ".join(f"{c}=EXCLUDED.{c}" for c in cols)
        sql = (
            f"INSERT INTO {table} ({', '.join(cols)}) VALUES ({placeholders}) "
            f"ON CONFLICT({conflict}) DO UPDATE SET {assignments}"
        )
    else:
        sql = (
            f"INSERT INTO {table} ({', '.join(cols)}) VALUES ({placeholders}) "
            f"ON CONFLICT({conflict}) DO NOTHING"
        )
    conn.execute(sql, [row[c] for c in cols])


def insert_many(conn: PgConn, table: str, rows: list[dict], conflict: str, replace: bool = False) -> None:
    if not rows:
        return
    cols = list(rows[0].keys())
    placeholders = ", ".join("?" for _ in cols)
    if replace:
        assignments = ", ".join(f"{c}=EXCLUDED.{c}" for c in cols)
        sql = (
            f"INSERT INTO {table} ({', '.join(cols)}) VALUES ({placeholders}) "
            f"ON CONFLICT({conflict}) DO UPDATE SET {assignments}"
        )
    else:
        sql = (
            f"INSERT INTO {table} ({', '.join(cols)}) VALUES ({placeholders}) "
            f"ON CONFLICT({conflict}) DO NOTHING"
        )
    conn.executemany(sql, [[row[c] for c in cols] for row in rows])


def has_row(conn: PgConn, sql: str, args=()) -> bool:
    return conn.execute(sql, args).fetchone() is not None


def status_of(conn: PgConn, dataset: str, month: str) -> dict | None:
    return conn.execute(
        "SELECT * FROM dataset_status WHERE dataset=? AND month=?",
        (dataset, month),
    ).fetchone()


def set_status(conn: PgConn, dataset: str, month: str, **kwargs) -> None:
    row = {
        "dataset": dataset,
        "month": month,
        "as_of_date": kwargs.get("as_of_date"),
        "status": kwargs.get("status", "PARTIAL"),
        "source": kwargs.get("source"),
        "source_url": kwargs.get("source_url"),
        "scraped_at": kwargs.get("scraped_at", now_iso()),
        "error": kwargs.get("error"),
    }
    upsert(conn, "dataset_status", row, "dataset, month")


def should_skip(conn: PgConn, dataset: str, month: str, current: bool) -> bool:
    if current:
        return False
    row = status_of(conn, dataset, month)
    return bool(row and row["status"] == "FINAL")


def fetchall(conn: PgConn, sql: str, args=()) -> list[dict]:
    return conn.execute(sql, args).fetchall()


def fetchone(conn: PgConn, sql: str, args=()) -> dict | None:
    return conn.execute(sql, args).fetchone()


def _maybe_migrate_sqlite(conn: PgConn) -> None:
    if not SQLITE_PATH.exists():
        return
    import sqlite3

    src = sqlite3.connect(SQLITE_PATH)
    src.row_factory = sqlite3.Row
    names = {r[0] for r in src.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    for table in TABLES:
        if table not in names:
            continue
        existing = conn.execute(f"SELECT COUNT(*) AS n FROM {table}").fetchone()
        if existing and existing["n"]:
            continue
        rows = [dict(r) for r in src.execute(f"SELECT * FROM {table}")]
        if not rows:
            continue
        if table == "scrape_runs":
            for row in rows:
                conn.execute(
                    """
                    INSERT INTO scrape_runs (started_at, finished_at, historical_updated,
                        historical_skipped, current_updated, errors, summary)
                    VALUES (?,?,?,?,?,?,?)
                    """,
                    (
                        row.get("started_at"),
                        row.get("finished_at"),
                        row.get("historical_updated") or 0,
                        row.get("historical_skipped") or 0,
                        row.get("current_updated") or 0,
                        row.get("errors") or 0,
                        row.get("summary"),
                    ),
                )
            conn.commit()
            continue
        conflict = _conflict_for(table)
        batch = []
        for row in rows:
            batch.append(row)
            if len(batch) >= 500:
                insert_many(conn, table, batch, conflict, replace=False)
                batch = []
        if batch:
            insert_many(conn, table, batch, conflict, replace=False)
        conn.commit()
    src.close()


def _conflict_for(table: str) -> str:
    mapping = {
        "dataset_status": "dataset, month",
        "institutional_flows": "month, category",
        "institutional_flow_daily": "trade_date, category",
        "sector_fpi_flows": "month, sector, period_type, period_end",
        "mutual_fund_flows": "month",
        "market_performance": "month",
        "sector_performance": "month, sector",
        "sector_relative_strength": "month, sector",
        "sector_money_flow_score": "month, sector",
        "daily_indices": "trade_date, index_name",
        "scrape_runs": "id",
    }
    return mapping[table]


def db_host() -> str:
    try:
        return urlparse(DATABASE_URL).hostname or ""
    except Exception:
        return ""


def print_status() -> None:
    init_db()
    conn = connect()
    print(f"connected  {db_host()}")
    print()
    empty = []
    for table in TABLES:
        n = conn.execute(f"SELECT COUNT(*) AS n FROM {table}").fetchone()["n"]
        flag = "ok" if n else "empty"
        print(f"  {flag:5}  {n:>8}  {table}")
        if not n:
            empty.append(table)
    latest = conn.execute("SELECT MAX(month) AS m FROM sector_money_flow_score").fetchone()
    run = conn.execute(
        "SELECT finished_at, summary FROM scrape_runs ORDER BY id DESC LIMIT 1"
    ).fetchone()
    print()
    print(f"latest scores month  {latest['m'] if latest and latest['m'] else 'none'}")
    if run:
        print(f"last scrape          {run['finished_at']}  {run['summary']}")
    print()
    if empty:
        print("empty tables:", ", ".join(empty))
    else:
        print("all tables have rows")
    conn.close()


if __name__ == "__main__":
    print_status()
